version: '3'
services:
  php5:
    image: "php:5.6-fpm"
    volumes:
      - .:/var/www/ci
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  mysql:
    image: "mysql:5.5"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  redis:
    image: "redis:alpine"
