version: '3'
services:
  php5:
    image: "ken/php56"
    volumes:
      - .:/var/www/ci
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  mysql:
    image: "mysql:5.5"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  redis:
    image: "redis:alpine"
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "1234"
    depends_on:
      - mysql
    ports:
      - 8888:80
